"""
plugins/tacops/ansible.py — Ansible обёртка

- Генерация ansible.cfg и requirements.yml
- Установка коллекций (Astra Automation Hub)
- Запуск плейбуков по фазам через bastion
"""
from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from typing import Optional

from plugins.tacops import find_tool

logger = logging.getLogger(__name__)


# ── Ansible playbook phases (из реального проекта 8297) ──────────────────────

PHASE_PLAYBOOKS = {
    "bastion": "01_bastion_setup.yml",
    "infrastructure": "02_infrastructure.yml",
    "aldpro": "03_aldpro_deployment.yml",
    "keycloak": "04_keycloak_docker.yml",
    "external_users": "05_external_users_setup.yml",
    "keycloak_apps": "06_keycloak_test_app.yml",
    "smartcards": "10_smartcard_setup.yml",
    "smartcard_test": "12_smartcard_auth_test.yml",
}

PHASE_ORDER = [
    "bastion", "infrastructure", "aldpro", "keycloak",
    "external_users", "keycloak_apps", "smartcards", "smartcard_test",
]


def generate_requirements_yml(collections: list[str]) -> str:
    """Сгенерировать requirements.yml для ansible-galaxy."""
    lines = ["---", "collections:"]
    for coll in collections:
        source = ""
        if coll.startswith("astra."):
            source = "published" if coll == "astra.ald_pro" else "validated"
        lines.append(f"  - name: {coll}")
        if source:
            lines.append(f"    source: {source}")
    return "\n".join(lines) + "\n"


def generate_ansible_cfg(inventory: str = "inventory.json",
                          galaxy_published_token: str = "",
                          galaxy_validated_token: str = "") -> str:
    """Сгенерировать ansible.cfg для стенда."""
    published_token_line = ""
    validated_token_line = ""
    if galaxy_published_token:
        published_token_line = f"token = {galaxy_published_token}"
    if galaxy_validated_token:
        validated_token_line = f"token = {galaxy_validated_token}"

    return f"""# Ansible config — generated by tacops
[defaults]
inventory = {inventory}
collections_paths = ~/.ansible/collections:/usr/share/ansible/collections
forks = 20
gathering = explicit
stdout_callback = yaml
host_key_checking = False

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=600s -o ServerAliveInterval=60
pipelining = True
timeout = 30

[galaxy]
server_list = published,validated

[galaxy_server.published]
url = https://hub.astra-automation.ru/api/galaxy
{published_token_line}

[galaxy_server.validated]
url = https://hub.astra-automation.ru/api/galaxy/content/validated/
{validated_token_line}
"""


# ── Запуск ansible-galaxy ────────────────────────────────────────────────────

def _run_ansible_galaxy(args: list[str], workdir: str,
                        timeout: int = 120) -> tuple[bool, str]:
    """Запустить ansible-galaxy."""
    binary = find_tool("ansible-galaxy")
    if not binary or binary == "ansible-galaxy":
        # fallback: system ansible-galaxy
        binary = "ansible-galaxy"
    cmd = [binary] + args
    logger.info("tacops: Running: %s", " ".join(cmd))
    try:
        r = subprocess.run(cmd, cwd=workdir, capture_output=True, text=True, timeout=timeout)
        return r.returncode == 0, r.stdout + r.stderr
    except subprocess.TimeoutExpired as e:
        return False, str(e)


def install_collections(workdir: str, requirements_file: str = "") -> tuple[bool, str]:
    """Установить Ansible коллекции."""
    req = requirements_file or f"{workdir}/requirements.yml"
    return _run_ansible_galaxy(
        ["collection", "install", "-r", req, "--force"],
        workdir=workdir,
        timeout=300,
    )


# ── Запуск ansible-playbook ──────────────────────────────────────────────────

def _run_ansible_playbook(playbook: str, inventory: str,
                          workdir: str, extra_vars: Optional[dict] = None,
                          timeout: int = 600) -> tuple[bool, str, dict]:
    """Запустить ansible-playbook.

    Возвращает (успех, вывод, сводка_фаз).
    """
    binary = find_tool("ansible-playbook")
    if not binary or binary == "ansible-playbook":
        binary = "ansible-playbook"

    env = {}

    cmd = [
        binary,
        "-i", inventory,
        playbook,
        "--ssh-common-args", (
            "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ),
    ]

    if extra_vars:
        for key, val in extra_vars.items():
            cmd.extend(["-e", f"{key}={val}"])

    logger.info("tacops: Running: %s", " ".join(cmd))
    try:
        import os as _os
        r = subprocess.run(
            cmd, cwd=workdir, capture_output=True, text=True,
            timeout=timeout, env={**_os.environ, **env},
        )
        ok = r.returncode == 0
        # Парсим сводку фаз из вывода
        summary = _parse_playbook_summary(r.stdout + r.stderr)
        return ok, r.stdout + r.stderr, summary
    except subprocess.TimeoutExpired as e:
        return False, str(e), {}


def _parse_playbook_summary(output: str) -> dict[str, str]:
    """Извлечь статус фаз из вывода ansible-playbook.

    Ищет строки вида:
        PLAY [Phase Name] ********************
        ...
        PLAY RECAP ***************************
        hostname : ok=X changed=Y failed=Z
    """
    summary = {}
    current_play = ""
    for line in output.split("\n"):
        if line.startswith("PLAY ["):
            current_play = line.replace("PLAY [", "").rstrip(" *").strip()
        if "failed=0" in line and current_play:
            summary[current_play] = "ok"
            current_play = ""
        elif "failed=" in line and current_play:
            import re
            m = re.search(r'failed=(\d+)', line)
            if m and int(m.group(1)) > 0:
                summary[current_play] = "failed"
            elif m:
                summary[current_play] = "ok"
            current_play = ""
    return summary


def run_phase(phase: str, inventory: str, workdir: str,
              extra_vars: Optional[dict] = None) -> tuple[bool, str, dict]:
    """Запустить одну фазу развёртывания.

    phase: bastion, infrastructure, aldpro, keycloak, ...
    """
    playbook = PHASE_PLAYBOOKS.get(phase)
    if not playbook:
        return False, f"Unknown phase: {phase}. Known: {list(PHASE_PLAYBOOKS.keys())}", {}

    playbook_path = Path(workdir) / playbook
    if not playbook_path.is_file():
        return False, f"Playbook not found: {playbook_path}", {}

    return _run_ansible_playbook(str(playbook_path), inventory, workdir, extra_vars)


def run_all_phases(inventory: str, workdir: str,
                   phases: Optional[list[str]] = None,
                   extra_vars: Optional[dict] = None) -> dict[str, dict]:
    """Запустить все фазы последовательно.

    Возвращает {фаза: {"ok": bool, "output": str, "summary": dict}}.
    """
    if phases is None:
        phases = PHASE_ORDER

    results = {}
    for phase in phases:
        logger.info("tacops: Phase %s starting...", phase)
        ok, output, summary = run_phase(phase, inventory, workdir, extra_vars)
        results[phase] = {"ok": ok, "output_preview": output[:500], "summary": summary}
        if not ok:
            logger.warning("tacops: Phase %s FAILED. Stopping.", phase)
            break
        logger.info("tacops: Phase %s OK.", phase)

    return results
